project:
  description: "Perl classes for interacting with Amazon SQS"
  author:
    name: Rob Lauer
    mailto: bigfoot@cpan.org
min-perl-version: 5.10.0
pm_module: Amazon::SQS::Client
dependencies:
    requires: requires
    test_requires: test-requires
    core_modules: no
extra-files:
  - ChangeLog
  - share:
      - examples
path:
  pm_module: src/main/perl/lib
  tests: src/main/perl/lib/t
  exe_files: src/main/perl/bin
  scripts: src/main/bash/bin
resources:
  homepage: 'https://git-codecommit.us-east-1.amazonaws.com/v1/repos/perl-Amazon-SQS-Client'
  repository:
    url: 'https://git-codecommit.us-east-1.amazonaws.com/v1/repos/perl-Amazon-SQS-Client'
    web: 'https://git-codecommit.us-east-1.amazonaws.com/v1/repos/perl-Amazon-SQS-Client'
    type: 'git'


