name: AmazonSQSClient
on: 
  push:
    branches: "*"
jobs:
  test-module:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rlauer6/bedrock-test:latest
      credentials:
        username: rlauer6
        password: ${{ secrets.DOCKER_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: build
        run: |
          cpanm -n -v Config::IniFiles AWS::Signature4 Proc::Daemon \
            Proc::PID::File Amazon::Credentials CGI::Simple Module::ScanDeps::Static
          ./bootstrap
          ./configure
          make
          cd cpan && PERL5LIB=/usr/local/share/perl5 make cpan
