name: AmazonSQSClient
on: 
  push:
    branches: "*"
jobs:
  test-module:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rlauer6/bedrock-test:latest
      credentials:
        username: rlauer6
        password: ${{ secrets.DOCKER_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: build
        run: |
          $(cat cpan/requires | perl -ne 'printf "cpanm -n -v %s~%s\n", grep {defined} split /\s+/, $_," 0";') || true
          ./bootstrap
          ./configure
          make
          cd cpan && PERL5LIB=/usr/local/share/perl5 make cpan
